Levelup
Teaching-projects/SZE-MOSZE-2020-Lekodolhatok--Closed pull request #5
Opened 2020-10-15 23:37 UTC by stefkamarton

@oliverosz
Kész a levelup!

2020-10-22 09:44 UTC, oliverosz requested changes

2020-10-22 09:44 UTC, oliverosz commented on .github/workflows/2-feladat.yml
> +        run: valgrind --error-exitcode=1 ./a.out kakarott.json makarott.json
majdnem jó, de még kell egy `--leak-check=full` is, különben nem minden hibát tekint errornak a valgrind

2020-10-22 09:44 UTC, oliverosz commented on .github/workflows/2-feladat.yml
> +        run: cppcheck *.cpp --enable=warning --output-file=list.txt
itt a style és performance hibákat kellene listázni, ha volt warning szintű hiba, akkor már az előző lépésnél úgyis elhasal

2020-10-22 09:44 UTC, oliverosz commented on .github/workflows/2-feladat.yml
> +          path: ./list.txt
a `list.txt` meg `lists` nem túl kifejező, legyen ennek valami beszélő neve

2020-10-22 09:44 UTC, oliverosz commented on character.cpp
> +	Character::XP = 0;
és ezek miért nem az inicializáló listában vannak inicializálva?

2020-10-22 09:44 UTC, oliverosz commented on character.cpp
> +	Character::Level++;
Egyrészt nem kellenek a scope-ok, a metóduson belül amúgy is scope-ban vannak a tagváltozók.
Másrészt hiányzik a kerekítés a növelésnél.
Harmadrészt nem jó a képlet, mert ha be van szorozva (level-1)-gyel, akkor ott elég nagy szorzókkal lesz beszorozva, duplázódni, triplázódni, stb. fog, és nem csak 10%-kal fog nőni. De az első szintlépésnél meg 0-val szorzódik, az meg kinullázza a maxHP-t és a sebzést, nem?

2020-10-22 09:44 UTC, oliverosz commented on character.cpp
> +		Character::XP = Character::XP + Character::DMG;
az elágazás igaz ágában nem kap xp-t

2020-10-22 09:44 UTC, oliverosz commented on character.cpp
> +		}
egy ütésből akár több szintet is léphet, ez nincs lekezelve

2020-10-22 09:44 UTC, oliverosz commented on character.h
> +	double levelUp(); //szintnoveles
ez ne legyen public

2020-11-03 20:38 UTC, oliverosz submitted a review, later dismissed

2020-11-03 20:38 UTC, oliverosz commented on .github/workflows/2-feladat.yml
> +        run: cppcheck *.cpp --enable=performance --output-file=cppcheck.txt
Az első hívásnál elég lett volna a warning szint, mert arra kell hibával leállítani a workflow-t, és a másodikhoz kellett volna felsorolni a style és performance kategóriákat (bár talán a performance amúgy is bekapcsolja a style-t)

2020-11-03 20:38 UTC, oliverosz commented on character.cpp
> +	MaxHP = HP;
Ez még mindig nem inicializáló listában inicializálódik.

2020-11-03 20:38 UTC, oliverosz commented on character.cpp
> +	int counter = XP % 100;
Ez nem jó. Ha 90 xp-je van, akkor 90 szintet lép?! Ha 180 xp-je van, akkor meg 80-at?!

2020-11-03 20:38 UTC, oliverosz commented on character.cpp
> +	return XP;
Az XP int típusú, a függvény meg double típust ad vissza...

2020-11-03 20:38 UTC, oliverosz commented on character.cpp
> +	if (Character::XP >= 100) {
Mivel ez ki lett szedve az else ágból, most mindenképp a teljes potenciális sebzésnek megfelelő XP-t kapja, akkor is, ha ténylegesen kevesebbet sebzett. Ez így nem jó.

2020-12-05 13:34 UTC, russiand96 approved these changes

2020-12-05 14:16 UTC, merged